### ISSUE TITLE
Cannot read property 'cleartext' of undefined

### ISSUE THREAD

**Issue by Gholbigrinn** [ProtonMail/pm-srp#4]
I get the following problem when i try to compile it on NodeJS

(node:9224) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'cleartext' of undefined
    at getCleartextMessage (D:\Sources\JS\pm-srp\node_modules\pmcrypto\lib\message\utils.js:46:17)
    at verifyAndGetModulus (D:\Sources\JS\pm-srp\lib\utils\modulus.js:59:78)
    at getSrp (D:\Sources\JS\pm-srp\lib\srp.js:203:32)
    at Object.<anonymous> (D:\Sources\JS\MySRP.js:19:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9224) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:9224) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mmso** [comment]
Try to setup the instance of pmcrypto with openpgp first https://github.com/ProtonMail/pmcrypto

```
import { init } from 'pmcrypto';

init(require('openpgp'));
```
